name: Release from main

on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Conventional Changelog Action
        id: release
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #- id: release
          #  uses: rymndhng/release-on-push-action@v0.15.0
          #  with:
          #    bump_version_scheme: patch

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag }}"
          echo "Got release version ${{ steps.release.outputs.version }}"

          #- uses: actions/checkout@v2
          #  with:
          #    # Disabling shallow clone is recommended for improving relevancy of reporting
          #    fetch-depth: 0

          #- name: Update package version
          #  uses: reedyuk/npm-version@1.0.1
          #  with:
          #    version: ${{ steps.release.outputs.version }}
