name: Release from main

on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fallback-version: 1.0.5
          skip-on-empty: 'false'
          output-file: 'false'
          release-count: 0
          skip-commit: 'true'
          #- id: release
          #  uses: rymndhng/release-on-push-action@v0.15.0
          #  with:
          #    bump_version_scheme: patch

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.changelog.outputs.tag }}"
          echo "Got release version ${{ steps.changelog.outputs.version }}"

      - name: Create Release
        uses: actions/create-release@v1
        #if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          #- uses: actions/checkout@v2
          #  with:
          #    # Disabling shallow clone is recommended for improving relevancy of reporting
          #    fetch-depth: 0

          #- name: Update package version
          #  uses: reedyuk/npm-version@1.0.1
          #  with:
          #    version: ${{ steps.release.outputs.version }}
