name: Release from main

on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Update package version
        uses: rimonhanna/gh-action-bump-version@master
        id: version
        with:
          tag-prefix: 'v'

      - name: Create Release
        uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: Release ${{ steps.version.outputs.tag }}

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.version.outputs.tag }}"
          echo "Got release version ${{ steps.version.outputs.tag }}"
